server:
  port: 18081 # 服务端口
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.6.41:5432/ting_user?useSSL=false&currentSchema=users
    username: ting_user_app
    password: Aa@123456

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl