<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.tingshuo</groupId>
    <artifactId>tingshuo-pro</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <!--听说项目alibaba相关开源项目-->
    <description>tingshuo-pro</description>
    <packaging>pom</packaging>
    <properties>
        <java.version>1.8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <!--全局配置springboot版本-->
        <spring-boot.version>2.7.8</spring-boot.version>
        <!--全局配置springCloud版本-->
        <spring-cloud.version>2021.0.8</spring-cloud.version>
        <!--全局配置SpringCloudAlibaba版本-->
        <spring-cloud-alibaba.version>2021.0.5.0</spring-cloud-alibaba.version>
        <!--全局配置nacos客户端版本-->
        <nacos.client.version>2.2.3</nacos.client.version>
        <seata.version>1.4.2</seata.version>
    </properties>
    <modules>
        <!--听说网关模块-->
        <module>gateway</module>
        <!--听说调度模块-->
        <module>job</module>

        <!--公共模块-->
        <module>common</module>
        <module>common/common-db</module>
        <module>common/common-mq</module>
        <module>common/common-redis</module>
        <module>common/common-web</module>
        <module>common/common-nacos-dc</module>
        <!--业务类模块拆分开始-->
        <module>services</module>
        <!--听说AI智能模块-->
        <module>services/ai-service</module>
        <!--听说用户模块-->
        <module>services/user-service</module>
        <!--听说资产模块-->
        <module>services/asset-service</module>
        <!--听说商品模块-->
        <module>services/product-service</module>
        <!--听说订单模块-->
        <module>services/order-service</module>
        <!--听说库存模块-->
        <module>services/storage-service</module>
        <!--业务类模块拆分结束-->
    </modules>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <!--nacos客户端配置-->
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>${nacos.client.version}</version>
        </dependency>


    </dependencies>
    <dependencyManagement>
        <dependencies>
            <!-- SpringBoot依赖配置 -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!-- SpringCloud 微服务 -->
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <!--SpringCloudAlibaba核心配置-->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${spring-cloud-alibaba.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.tingshuo</groupId>
                <artifactId>common-nacos-dc</artifactId>
                <version>${project.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

</project>
