server:
  port: 18085
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.6.41:5432/ting_product?useSSL=false&currentSchema=products
    username: ting_product_app
    password: Aa@123456

mybatis-plus:
  configuration:
    use-generated-keys: true # 开启主键回填
    map-underscore-to-camel-case: true # 开启下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # id-type: auto
      insert-strategy: IGNORED   # ← 强制所有字段参与 INSERT，包括 id=null