server:
  port: 18080 # 服务端口
#  jwt 配置
jwt:
  # jwt 密钥
  secret: RxGsCE/ZfSnCiFJMtLjAKDYlib/na2QqNk//hSXOt3SOJHFo0I6qAa8wm6IyrPyDtfaZ2E9db/0Aue8qon9N3g==
  expiration: 86400000 # token 过期时间
  header: Authorization # jwt 请求头
  tokenPrefix: Bearer # jwt 前缀




# 确保日志输出正常
logging:
  level:
    com.tingshuo: DEBUG


spring:
  # redis 配置
  redis:
    host: 192.168.6.41
    port: 6379
    password: 123456
    database: 1
  # spring cloud gateway 配置
  cloud:
    gateway:
      routes: # 路由配置
        # ========== 用户服务 ==========
        - id: tingshuo-user-route # 用户路由id
          uri: lb://tingshuo-user # 用户服务地址
          predicates:
            - Path=/user/** # 路径匹配
        - id: tingshuo-asset-route # 资产服务地址路由id
          uri: lb://tingshuo-asset # 资产服务地址
          predicates:
              - Path=/deposit/** # 匹配路径
        # ========== 订单服务 ==========
        - id: tingshuo-order-route
          uri: lb://tingshuo-order
          predicates:
              - Path=/order/**
        # ========== 库存服务 ==========
        - id: tingshuo-storage-route
          uri: lb://tingshuo-storage
          predicates:
              - Path=/storage/**
        # ========== 商品服务 ==========
        - id: tingshuo-product-route
          uri: lb://tingshuo-product
          predicates:
              - Path=/product/**
        # ========== 认证服务 ==========
        - id: tingshuo-auth-route
          uri: lb://tingshuo-auth
          predicates:
            - Path=/api/auth/**
        # ========== 优惠券服务 ==========
        - id: tingshuo-coupon-user-route
          uri: lb://tingshuo-coupon
          # 优惠券服务 单独配置 核销接口流量控制
          predicates:
            - Path=/api/coupon/internal/use
        - id: tingshuo-coupon-route
          uri: lb://tingshuo-coupon
          predicates:
            - Path=/api/coupon/**



    # sentinel 限流配置
    sentinel:
      enabled: true # 启用Sentinel
      eager: true # 立即初始化Sentinel，避免懒加载导致首次调用无保护
      transport:
        #dashboard: 192.168.6.41:19080 # sentinel 控制台地址
        dashboard: 127.0.0.1:19080 # sentinel 控制台地址
        port: 8719 # sentinel 端口
      datasource:
        ds1: # sentinel 配置
          nacos:
            server-addr: 192.168.6.41:8848
            username: nacos
            password: Aa123456_
            namespace: tingshuo-pro
            group-id: DEFAULT_GROUP
            data-id: gateway-flow-rules # 配置文件名称
            data-type: json #  配置文件类型
            rule-type: gw-flow # 网关限流规则