<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.tingshuo</groupId>
        <artifactId>tingshuo-pro</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <packaging>pom</packaging>
    <artifactId>services</artifactId>
    <description>业务类模块</description>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <modules>
        <module>user-service</module>
        <module>asset-service</module>
        <module>product-service</module>
        <module>order-service</module>
        <module>storage-service</module>
        <module>ai-service</module>
        <module>asset-service</module>
        <module>auth-service</module>
        <module>auth-service/auth-api</module>
        <module>auth-service/auth-biz</module>
    </modules>

</project>