registry {
  type = "nacos"
  nacos {
    application = "seata-server"
    serverAddr = "192.168.6.41:8848"
    group = "DEFAULT_GROUP"      # 注册中心必须用 DEFAULT_GROUP
    namespace = "tingshuo-pro"    # 如果用了自定义命名空间
    cluster = "default"
    username = "nacos"
    password = "Aa123456_"
  }
}

config {
  type = "nacos"
  nacos {
    serverAddr = "192.168.6.41:8848"
    group = "SEATA_GROUP"        # 配置中心必须用 SEATA_GROUP
    namespace = "seata"    # 命名空间 ID（与 Nacos 中一致）
    username = "nacos"
    password = "Aa123456_"
    # dataId = "seataServer.properties"  # ❌ 不要加
  }
}
