# ======================== Registry ========================
registry.type=nacos
registry.nacos.application=seata-server
registry.nacos.server-addr=192.168.6.41:8848
registry.nacos.group=DEFAULT_GROUP
registry.nacos.namespace=tingshuo-pro
registry.nacos.username=nacos
registry.nacos.password=Aa123456_
registry.nacos.cluster=default
registry.nacos.ip=192.168.6.41

# ======================== Config Center ========================
config.type=nacos
config.nacos.server-addr=192.168.6.41:8848
config.nacos.group=SEATA_GROUP
config.nacos.namespace=tingshuo-pro
config.nacos.username=nacos
config.nacos.password=Aa123456_

# ======================== Server ========================
server.service-port=8091
server.recovery.committing-retry-period=1000
server.recovery.async-committing-retry-period=1000
server.recovery.rollbacking-retry-period=1000
server.recovery.timeout-retry-period=1000

# ======================== Security ========================
security.secretKey=SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
security.tokenValidityInMilliseconds=86400000
security.ignore.urls=/,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/api/v1/auth/login

# ======================== Store ========================
store.mode=db
store.lock.mode=db
store.session.mode=db
store.db.datasource=druid
store.db.dbType=postgresql
store.db.driverClassName=org.postgresql.Driver
store.db.url=jdbc:postgresql://192.168.6.41:5432/ntdb?useUnicode=true&stringtype=unspecified
store.db.user=nantian
store.db.password=PG@202512
store.db.minConn=5
store.db.maxConn=30
store.db.globalTable=global_table
store.db.branchTable=branch_table
store.db.lockTable=lock_table
store.db.distributedLockTable=distributed_lock
store.db.queryLimit=100
store.db.maxWait=5000

# ======================== Transport ========================
# ???????????
transport.type=TCP
transport.server=NIO
transport.heartbeat=true
transport.enableTmClientBatchSendRequest=false
transport.enableRmClientBatchSendRequest=true
transport.rpcRmRequestTimeout=30000
transport.rpcTmRequestTimeout=30000
transport.shutdown.wait=3
# ======================== Service ========================
service.vgroupMapping.my_tx_group=default

# ?????????? server ????? true?
store.db.distributed-lock=true

# ?????
transport.threadFactory.bossThreadPrefix=NettyBoss
transport.threadFactory.workerThreadPrefix=NettyServerNIOWorker
transport.threadFactory.serverExecutorThreadPrefix=NettyServerBizHandler
transport.threadFactory.shareBossWorker=false
transport.threadFactory.clientSelectorThreadPrefix=NettyClientSelector
transport.threadFactory.clientSelectorThreadSize=1
transport.threadFactory.clientWorkerThreadPrefix=NettyClientWorkerThread
transport.threadFactory.bossThreadSize=1
transport.threadFactory.workerThreadSize=default

# ========================
# ????????TM/RM?
# ========================
client.tm.commitRetryCount=5
client.tm.rollbackRetryCount=5
client.tm.defaultGlobalTransactionTimeout=60000
client.tm.degradeCheck=false
client.tm.degradeCheckAllowTimes=10
client.tm.degradeCheckPeriod=2000

client.rm.asyncCommitBufferLimit=10000
client.rm.reportRetryCount=5
client.rm.tableMetaCheckEnable=false
client.rm.sqlParserType=druid
client.rm.reportSuccessEnable=false
client.rm.sagaBranchRegisterEnable=false

# ========================
# ????AT ???
# ========================
lock.mode=db
lock.db.wait-time=50000

# ========================
# ?????????
# ========================
metrics.enabled=false
metrics.registryType=compact
metrics.exporterList=prometheus
metrics.exporterPrometheusPort=9898